FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash rito

RUN mkdir /etc/rito

RUN mkdir /var/lib/rito

RUN chown rito:rito /etc/rito /var/lib/rito

WORKDIR /home/rito

COPY --chown=rito:rito linux64/* ./run.sh /home/rito/

USER rito

CMD ["/home/rito/run.sh"]
